# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://zoohair.github.io

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty


