# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://zoohair.github.io

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty


plugins:
  - jekyll-seo-tag


social:
  - title: linkedin
    url: https://linkedin.com/in/zouhairm
  - title: github
    url: https://github.com/zoohair
  - title: facebook
    url: https://facebook.com/zoohair


description: Different projects Zouhair worked on during his career
author: Zouhair Mahboubi

